title: Aladin Virmaux
author: Aladin Virmaux
tagline: Researcher in Machine Learning

name: Aladin Virmaux
email: aladin.virmaux@huawei.com
description: Aladin Virmaux Professional webpage

domain: avirmaux.github.io
url: https://avirmaux.github.io

twitter_username: Monoideabelien
github_username:  avirmaux

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
