title: Aladin Virmaux
email: aladin.virmaux@huawei.com
description: >- # this means to ignore newlines until "baseurl:"
    Personal page of Aladin Virmaux

domain: avirmaux.github.io
url: https://avirmaux.github.io

twitter_username: Monoideabelien
github_username:  avirmaux

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
